<?php
$sources = News::getSources();
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<table class="table">
    <tr>
        <td>媒體</td>
        <td>標題</td>
        <td>時間</td>
        <td>網址</td>
    </tr>
<?php foreach ($this->news_array as $news) { ?>
<?php $first_info = $news->infos->ordeR('time ASC')->first(); ?>
    <?php foreach ($news->infos as $info) { ?>
    <tr>
        <td><?= $this->escape($sources[$news->source]) ?></td>
        <td><?= $info->title ?></td>
        <td><a href="/index/log/<?= $news->id ?>#<?= $info->time ?>"><?= date('c', $info->time) ?></a></td>
        <td><?= $this->escape($news->url) ?></td>
    </tr>
    <?php } ?>
<?php } ?>
</table>
<?= $this->partial('/common/footer.phtml', $this) ?>
