<script>
	function exportCsv()
	{
		var x = window.location + "&iscsv=1";
		window.location = x;
	}
	function exportSma()
	{
		var x = window.location + "&issma=1";
		window.location = x;
	}
</script>
<?php
$sources = News::getSources();
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<?php if (count($this->search_array)): ?>
	<button onclick="exportCsv();">Export CSV</button>
	<button onclick="exportSma();">Export IBM SMA Format</button>
<table class="table">
    <tr>
        <td>媒體</td>
        <td>標題</td>
        <td>時間</td>
    </tr>
	<?php foreach ($this->search_array as $news) { ?>
		<tr>
			<td><?= $this->escape($sources[$news["source"]]) ?></td>
			<td><a class="btn btn-info" href="http://newsdiff.g0v.ronny.tw/index/search?q=<?= $this->escape($news['url']) ?>" target="_blank">diff</a> <a href="/index/log/<?= $news["id"] ?>#<?= $news["time"] ?>"><?= $news["title"] ?></a></td>
			<td><?= date("Y-m-d H:i:s", $news["time"]) ?></td>
		</tr>
	<?php } ?>
	</table>
<?php endif;?>
<?php if (count($this->news_array)): ?>
	<table class="table">
		<tr>
			<td>媒體</td>
			<td>標題</td>
			<td>時間</td>
		</tr>
<?php endif; ?>
<?php foreach ($this->news_array as $news) { ?>
<?php $first_info = $news->infos->ordeR('time ASC')->first(); ?>
    <?php foreach ($news->infos as $info) { ?>
    <tr>
        <td><?= $this->escape($sources[$news->source]) ?></td>
        <td><a class="btn btn-info" href="http://newsdiff.g0v.ronny.tw/index/search?q=<?= $this->escape($news->url) ?>" target="_blank">diff</a> <a href="/index/log/<?= $news->id ?>#<?= $info->time ?>"><?= $info->title ?></a></td>
        <td><?= date('Y-m-d H:i:s', $info->time) ?></td>
        <!--<td><?= $this->escape($news->url) ?></td>-->
    </tr>
    <?php } ?>
<?php } ?>
<?php if (count($this->news_array)): ?>
</table>
<?php endif; ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
